// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_toggle  22
#define SYS_print_count  23
#define SYS_add 24
#define SYS_ps 25
#define SYS_halt 26
#define SYS_create_container 27
#define SYS_destroy_container 28
#define SYS_join_container 29
#define SYS_leave_container 30
#define SYS_proc_container 31
#define SYS_proc_container_num 32
#define SYS_scheduler_log_on 33
#define SYS_containerProcessNum 34
#define SYS_check_schedule_log 35
#define SYS_memory_log_on 36
#define SYS_check_memory_log 37
#define SYS_file_creation_log 38
#define SYS_check_file_creation 39
#define SYS_isAllEnded 40
#define TotaleSysNum 40

